---
title: Mon blog avec Jekyll
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
email: picarddamien@outlook.com
description: ''
baseurl: 'jekyll-test'
url: ''
twitter_username: CuicuiPikpik
github_username: MrPikpikLol
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
